### ISSUE TITLE
Fix test bug wrt failing to delete Mongo files

### ISSUE THREAD

**Issue by MrCreosote** [kbase/workspace_deluxe#554]
```
   [junit] Unable to delete file: workspace_test_temp/MongoController-12363934856173074220/data/diagnostic.data/metrics.interim
    [junit] java.io.IOException: Unable to delete file: workspace_test_temp/MongoController-12363934856173074220/data/diagnostic.data/metrics.interim
    [junit] 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
    [junit] 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
    [junit] 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
    [junit] 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
    [junit] 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
    [junit] 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
    [junit] 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
    [junit] 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
    [junit] 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
    [junit] 	at us.kbase.common.test.controllers.mongo.MongoController.destroy(MongoController.java:82)
    [junit] 	at us.kbase.workspace.test.kbase.JSONRPCLayerTester.tearDownClass(JSONRPCLayerTester.java:472)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 
    [junit] Test us.kbase.workspace.test.kbase.JSONRPCLayerTest FAILED
```
This is actually an issue in https://github.com/kbase/java_common but it's way more likely to get fixed if I post here. 
Probably a race condition with mongo shutting down and deleting stuff and the directory delete happening at the same time

**Comment by MrCreosote** [comment]
Still occurring. Next thing to try is a loop with logging so that if that doesn't work we have a better idea of what's going on.

**Comment by MrCreosote** [comment]
Turns out the fix wasn't applied correctly to the workspace. Applied here: https://github.com/kbase/workspace_deluxe/pull/645
